# This is a basic workflow to help you get started with Actions

name: HttpServer CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # setup dotnet environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ''

      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore
      
      # Builds project. the --configuration Release flag compiles project in release mode for optimal performance
      - name: Build project
        run: dotnet build --configuration Release --no-restore

      # runs tests
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal
        

